services:
  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: ${POSTGRES_RESTART_STATUS}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: POSTGRES_DATABASE
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:${POSTGRES_VOLUMES}

  redis:
    image: ${REDIS_IMAGE}
    container_name: ${REDIS_CONTAINER_NAME}
    restart: ${REDIS_RESTART_STATUS}
    ports:
      - "${REDIS_PORT}:6379"
volumes:
  pg_data:
    driver: local